import "./globals.css";
import Header from "./header";
import Footer from "./footer";

export const metadata = {
  title: "Acme",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative h-lvh ">
        <Header />
        <section className="font-sans  font-light px-8  ">{children}</section>
        <Footer />
      </body>
    </html>
  );
}
